/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.calcite.poc.CalcitePOC;

public class App {
    public static void main(String[] args) {
        CalcitePOC poc = new CalcitePOC();
        poc.run();
    }
}
