repos:
  - repo: local
    hooks:
      - id: spotless-check
        name: Spotless Check
        entry: ./gradlew spotlessCheck
        language: system
        pass_filenames: false
        always_run: true
