repos:
  - repo: local
    hooks:
      - id: spotless-format
        name: Spotless Format
        entry: bash -c './gradlew spotlessApply && git diff --name-only --cached | xargs git add'
        language: system
        pass_filenames: false
