repos:
  - repo: local
    hooks:
      - id: spotless-format
        name: Spotless Format
        entry: bash -c './gradlew spotlessApply && ./gradlew spotlessCheck && git add -u'
        language: system
        pass_filenames: false
