/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appRunsWithoutException() {
        // Basic smoke test to ensure the app doesn't throw exceptions
        assertDoesNotThrow(() -> {
            // We could run the main method here if needed
            // App.main(new String[]{});
        });
    }
}
